### ISSUE TITLE
Versions of Magento supported

### ISSUE THREAD

**Issue by maderlock** [magento/mtf#10]
There seems to be an assumption in the documentation that this will be used with Magento 2. However, CE 1.9.2 seems to include MTF tests. Does that mean that this framework supports Magento 1? Further, can it only be used for CE >= 1.9.2?

**Comment by lanken** [comment]
Yes, MTF is used for functional test creation both for Magento 1 and Magento 2

**Comment by mage2travis** [comment]
Please answer on GitHub…

**Comment by lanken** [comment]
Closed, feel free to reopen in case if you still have questions.

**Comment by maderlock** [comment]
Thanks.  Can it only be used for CE >= 1.9.2?

**Comment by lanken** [comment]
Actually it can be used for any Magento version, but for previous version functional tests weren't published with Magento code base. You can try to port tests from the latest Magento to required Magento version, the core functionality wasn't changed so the only what you will need is to update selectors and store fron blocks according to the theme.

**Comment by lanken** [comment]
Closed, feel free to reopen in case if you still have questions.
