### ISSUE TITLE
Invalid username or password when running mtf tests

### ISSUE THREAD

**Issue by ronlinet** [magento/mtf#13]
Getting error “Invalid username or password” when selenium server tries to login to Admin Panel => 
http://magento/index.php/admin/permissions_role/index . 
The username and password are correct because I can manually login to the same url even with the same browser. 
I have tried this solution => http://stackoverflow.com/questions/13860936/magento-cant-login-in-admin-with-right-username-and-password  but it doesn't work in my case. 
Is there any other php/xml config file where I can override the login values?

**Comment by dshevtsov** [comment]
@ronlinet please check the following topic - http://devdocs.magento.com/guides/v2.0/mtf/mtf_quickstart/mtf_quickstart_config.html
I hope this helps

**Comment by lanken** [comment]
Please, check that 'app_backend_url' in phpunit.xml is the same as for your application after you have been logged in to admin.

**Comment by ronlinet** [comment]
Filling the correct backendLogin and backendPassword  in config.xml does the trick. 
@dshevtsov link has further details regarding the fix.
