### ISSUE TITLE
Testdata aren´t complete

### ISSUE THREAD

**Issue by sjauck** [magento/mtf#15]
The Testdata aren´t complete. 
For example the frontend customer login can´t work because the initialCustomer data aren´t present.

Please complete.

**Comment by lanken** [comment]
Hi @sjauck, 
Could you, please, specify the test in what this problem is occurred.
Did you mean dev/tests/functional/tests/app/Magento/Customer/Test/TestCase/UpdateCustomerFrontendEntityTest.php?

**Comment by sjauck** [comment]
Hi.

Yes this is the test i found atm.

**Comment by lanken** [comment]
What test data do you need?
$initialCustomer loads data from default data set for the Customer fixture that in placed in dev/tests/functional/tests/app/Magento/Customer/Test/Repository/Customer.xml
    
        <dataset name="default">
            <field name="firstname" xsi:type="string">John</field>
            <field name="lastname" xsi:type="string">Doe</field>
            <field name="group_id" xsi:type="array">
                <item name="dataset" xsi:type="string">General</item>
            </field>
            <field name="email" xsi:type="string">JohnDoe_%isolation%@example.com</field>
            <field name="password" xsi:type="string">123123q</field>
            <field name="password_confirmation" xsi:type="string">123123q</field>
        </dataset>

Have you run generator http://devdocs.magento.com/guides/v2.0/mtf/mtf_quickstart/mtf_quickstart_environmemt.html#mtf_quickstart_env_generator

**Comment by sjauck** [comment]
Hi. Yes this is the data and yes i run the generator. :)

After deleting the generated classes by hand and regenerate again. It work now.

**Comment by lanken** [comment]
You are welcome.
It's strange that you had to delete classes manually, they should be recreated after running generator.
If you will face with this again, feel free to reopen the issue.
