### ISSUE TITLE
Autoloading Constraints

### ISSUE THREAD

**Issue by sjauck** [magento/mtf#16]
Hello.
Atm i write a testcase for customer in frontend. 
For the test cases i add a new folder in functional/tests/app/ for the module. 
The Test cases in this folder can be run without problem. But if i try to add Constraints in my Module/Test folder. This constraint can´t be found. If i copy the Constraint to the Magento Folder, it can be found. Is there a restriction for the place of Constraints?

**Comment by lanken** [comment]
Hi @sjauck 
There is no limitation for constraint placement.
Could you, please, provide a code for your variation file and constraint class.

**Comment by sjauck** [comment]
First i try to add them in app/code/NAMESPACE but there was no chance to get the tests to run. 
So i locate threm in dev/tests/app/NAMESPACE/MODULE.
NAMESPACE != Magento
My constraint is in dev/tests/app/NAMESPACE/MODULE/Test/Constraint
Filename: AssertMyAccountPageIsAvailable
Code: 
namespace NAMESPACE\MODULE\Test\Constraint;

use Magento\Mtf\Constraint\AbstractConstraint;
use NAMESPACE\MODULE\Test\Page\CustomerAccountSubaccounts;

class AssertMyAccountPageIsAvailable extends AbstractConstraint
{
    const ERROR_TEXT = '404 Error';

    /**
     * Assert that MyAccount page has correct title and 404 Error is absent on the page.
     *
     * @param CustomerAccountSubaccounts $customerAccountSubaccounts
     * @param string $pageTitle
     * @return void
     */
    public function processAssert(CustomerAccountSubaccounts $customerAccountSubaccounts, $pageTitle)
    {
        \PHPUnit_Framework_Assert::assertEquals(
            $pageTitle,
            $customerAccountSubaccounts->getTitleBlock()->getTitle(),
            'Invalid page title is displayed.'
        );
        \PHPUnit_Framework_Assert::assertNotContains(
            self::ERROR_TEXT,
            $customerAccountSubaccounts->getErrorBlock()->getContent(),
            "404 Error is displayed on '$pageTitle' page."
        );
    }

    /**
     * Returns a string representation of the object.
     *
     * @return string
     */
    public function toString()
    {
        return 'MyAccount has correct title and 404 page content is absent.';
    }
}

My variation File is in dev/tests/app/NAMESPACE/MODULE/Test/TestCase
Code:
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../vendor/magento/mtf/etc/variations.xsd">
    <testCase name="NAMESPACE\MODULE\Test\TestCase\NavigateMenuMyAccountTest" summary="Check Navigate MyAccount Page">
        <variation name="CheckMyAccountPage1" summary="Check MyAccount Page">
            <data name="initialCustomer/data/firstname" xsi:type="string">Jany %isolation%</data>
            <data name="initialCustomer/data/lastname" xsi:type="string">Doe %isolation%</data>
            <data name="initialCustomer/data/email" xsi:type="string">janydoe%isolation%@example.com</data>
            <data name="initialCustomer/data/is_subscribed" xsi:type="string">No</data>
            <data name="initialCustomer/data/password" xsi:type="string">test%isolation%</data>
            <data name="initialCustomer/data/password_confirmation" xsi:type="string">test%isolation%</data>
            <data name="pageTitle" xsi:type="string">Subaccounts</data>
            <constraint name="NAMESPACE\Subaccounts\Test\Constraint\AssertMyAccountPageIsAvailable" />
            <constraint name="Magento\Customer\Test\Constraint\AssertCustomerLogout" />
        </variation>
    </testCase>
</config>

My error message:
InvalidArgumentException: Cannot generate class "Dotsource\Subaccounts\Test\Constraint\AssertMyAccountPageIsAvailable". Unknown type constraint

**Comment by lanken** [comment]
Now I got your problem.
In order to solve it you should update `autoload` section in __dev/tests/functional/composer.json__ file. You should specify where to find your classes
```
    "autoload": {
        "psr-4": {
            "Magento\\": ["lib/Magento/", "testsuites/Magento", "generated/Magento/", "tests/app/Magento/"],
            "Dotsource\\": ["tests/app/Dotsource/"],
            "Test\\": "generated/Test/"
        }
    }
```

**Comment by sjauck** [comment]
Great now it work. :) 
This i didn´t looked. 

Thx.

**Comment by lanken** [comment]
It's not MTF logic, TestCase class is run explicitly in your case, so autoloader is not participate in looking for it.

**Comment by sjauck** [comment]
Ok. Thx.
