### ISSUE TITLE
Problems with more then one TestCase

### ISSUE THREAD

**Issue by sjauck** [magento/mtf#17]
I wrote some Testcases. They are located in one Module Directory in dev/tests/functional/app/X.

If i run every Test alone with the command:
./vendor/bin/phpunit -c phpunit.xml --debug --coverage-html "/var/www/html/magento2/report" --filter "TestCaseX"
it work. But if i try to run all tests in the directory, the first test work but every other test didn´t work, because the browser connected to Selenium didn´t open the page, it stay blank.

After i searched the Code for a solution i come to Magento\Mtf\Client\Browser there i deactivated the functioon reopen() and the tests run completely. 

Now i am not sure is it a back in MTF, Selenium or is a configuration at my System wrong?

My Versions:
magento/mtf: 1.0.0-rc40
Selenium i tried: 
selenium-server-standalone-2.49.0.jar
selenium-server-standalone-2.49.1.jar
selenium-server-standalone-2.50.0.jar
selenium-server-standalone-2.50.1.jar
selenium-server-standalone-2.52.0.jar

Browser: Mozilla Firefox 44.0

My Config Value for the Selenium Server:
```
<server>
        <item name="selenium" type="default" browser="Mozilla Firefox" browserName="firefox" host="172.17.0.1" port="4444" seleniumServerRequestsTimeout="90" sessionStrategy="shared">
            <desiredCapabilities>
                <platform>ANY</platform>
            </desiredCapabilities>
        </item>
    </server>
```

**Comment by lanken** [comment]
Hi @sjauck,

Please, try the latest MTF release 1.0.0-rc41. It seems that the issue has been fixed in it.

**Comment by sjauck** [comment]
Hi @lanken,
yes it work with  MTF release 1.0.0-rc41. Thx for feedback.
Issue can be closed.
