### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by Ali-Muhammad-Esmaelgee** [magento/mtf#21]
Hi

I have recently just started working on MTF for magento 1 mostly and been really interested about the framework. Though, I just hit a wall and was wondering is there was a method to override values present in the fixture Data sources files from the Data Set or Repository. Those hardcoded values in the Fixture Data Source makes it very difficulty to add flexilibility to the tests.

**Comment by lanken** [comment]
Hi @Ali-Muhammad-Esmaelgee,

Currently in that version of framework that is used in Magento 1 there is no easy way to override data source values. With the next release M1 will be updated to newer framework version where such ability is implemented, it will be use the same approcah as Magento 2 does.

**Comment by Ali-Muhammad-Esmaelgee** [comment]
Hi @lanken  Thanks for this feedback. 

Can i also request for a way to add summary or ticket number to datasets. those are really very helpful pieces of information when running the test, specially for all the different variations. Currently you can only see test case #1, test case #2,... and thats not very helpful, and that too when you enable the debuggind mode. 

Regard 
Ali yassar

**Comment by lanken** [comment]
@Ali-Muhammad-Esmaelgee,
Did you mean something like this https://github.com/magento/magento2/blob/develop/dev/tests/functional/tests/app/Magento/Catalog/Test/TestCase/Product/UpdateSimpleProductEntityTest.xml#L120?
In this case ticket number is not shown in phpunit result, it's just for linkage.

If, yes, it will be also available with the next M1 release.
Now as a workaround, I could suggest you to use ticket number in variation names.

**Comment by Ali-Muhammad-Esmaelgee** [comment]
yeps that exactly what im talking about.... may i know when is the next release?

**Comment by lanken** [comment]
M1 release will be approximately in May.
Regarding variation names, you could name you own variation as you like.

**Comment by Ali-Muhammad-Esmaelgee** [comment]
I think i would just wait until next release. because i cant get the desired information printed out in the logs. Anyways thanks for the info. I am leaving this thread for you to decide whether this should get closed or not.

**Comment by lanken** [comment]
Closed. Feel free to reopen in case of any questions or create new issue.
