### ISSUE TITLE
functional test: Unknown type block

### ISSUE THREAD

**Issue by naveenabt** [magento/mtf#23]
Hi,

I am executing the functional test for custom module.
I am getting below error.

Namespace\Module\Test\TestCase\CreatePincodeEntityTest::test with data set "CreatePincodeEntityTestVariation1" (CreatePincodeEntityTestVariation1)
InvalidArgumentException: Cannot generate class "Namespace\Module\Test\Block\Adminhtml\Pincode\Edit\PincodeForm". Unknown type block
in /dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Code/Generator.php:62

How to solve the above error.

If i run generate.php, getting same error.

Thanks

**Comment by lanken** [comment]
As I understand, you create test in you custom namespace.
Please, try
https://github.com/magento/mtf/issues/16#issuecomment-182752526

**Comment by naveenabt** [comment]
Thank you Ianken!
Yes, I created the test in custom namespace. Added the below code to composer.json
```
    "autoload": {
        "psr-4": {
            "Magento\\": ["lib/Magento/", "testsuites/Magento", "generated/Magento/", "tests/app/Magento/"],
            "Namespace\\": ["tests/app/Namespace/"],
            "Test\\": "generated/Test/"
        }
    }
```
Ran the command 
`composer dump-autoload`
But the issue remains, when we run both
`php generate.php`
and 
`phpunit --filter CreatePincodetemplateEntityTest --debug`
we get the same error
`InvalidArgumentException: Cannot generate class "Namespace\Pincodetemplate\Test\Block\Adminhtml\Pincodetemplate\Edit\PincodetemplateForm". Unknown type block`

Please suggest..

**Comment by naveenabt** [comment]
The PincodetemplateForm.php has the code
```
namespace Namespace\Pincodetemplate\Test\Block\Adminhtml\Edit;
use Magento\Mtf\Block\Form as ParentForm;
class PincodetemplateForm extends ParentForm
{
    //
}
```

**Comment by naveenabt** [comment]
```
PHP Fatal error:  Uncaught InvalidArgumentException: Cannot generate class "Namespace\Pincodetemplate\Test\Block\Adminhtml\Pincodetemplate\Edit\PincodetemplateForm". Unknown type block in /var/www/magee204/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Code/Generator.php:62
Stack trace:
#0 /var/www/magee204/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Code/Generator/Autoloader.php(37): Magento\Mtf\Code\Generator->generateClass('Namespace\\Pincode...')
#1 [internal function]: Magento\Mtf\Code\Generator\Autoloader->load('Namespace\\Pincode...')
#2 [internal function]: spl_autoload_call('Namespace\\Pincode...')
#3 /var/www/magee204/dev/tests/functional/lib/Magento/Mtf/Util/Generate/Factory/AbstractFactory.php(208): ReflectionClass->__construct('\\Namespace\\Pincod...')
#4 /var/www/magee204/dev/tests/functional/lib/Magento/Mtf/Util/Generate/Factory/AbstractFactory.php(180): Magento\Mtf\Util\Generate\Factory\AbstractFactory->_processItem(Array, Array, '/var/www/mage-e...', 'tests/app', 'tests/app')
#5 /var/www/mage-ee in /var/www/magee204/dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Code/Generator.php on line 62
```

**Comment by lanken** [comment]
It's strange error, according to your class, you should get Namespace\Pincodetemplate\Test\Block\Adminhtml\Edit\PincodetemplateForm, but in stack trace you try to get Namespace\Pincodetemplate\Test\Block\Adminhtml\Pincodetemplate\Edit\PincodetemplateForm.
Please, check the place where you call this block.

**Comment by naveenabt** [comment]
@lanken, thank you for pointing out the difference. I overlooked it..
Corrected the namespace for the form class and it worked!
Thanks a lot!

**Comment by lanken** [comment]
You are welcome.

**Comment by rpeddinti** [comment]
nice
