### ISSUE TITLE
functional test: When we have to use Data set and Repository

### ISSUE THREAD

**Issue by naveenabt** [magento/mtf#24]
Hi,

When we have to use Data set and Repository.
I am having confusion with this, both having test variations.

Thanks,

**Comment by lanken** [comment]
Hi @naveenabt,

Data sets is used as test data for test cases: http://devdocs.magento.com/guides/v2.0/mtf/mtf_entities/mtf_dataset.html
Repository is just some predefined data for a particular fixture which can be used as data for a test: http://devdocs.magento.com/guides/v2.0/mtf/mtf_entities/mtf_fixture-repo.html

**Comment by naveenabt** [comment]
Thanks lanken..
