### ISSUE TITLE
functional test: Assert required fields

### ISSUE THREAD

**Issue by naveenabt** [magento/mtf#25]
HI,

I am writing functional test case and my module does not have any tab. I need to check the required fields in assertion.
Below code i have referred from customer module and customer module having Tab
Constraint Path: /dev/tests/functional/tests/app/Magento/Customer/Test/Constraint/AssertCustomerBackendRequiredFields.php

`public function processAssert(CustomerIndexNew $customerNewPage, array $expectedRequiredFields)
    {
        $actualRequiredFields = $customerNewPage->getCustomerForm()->getJsErrors();
        foreach ($expectedRequiredFields as $field) {
            \PHPUnit_Framework_Assert::assertTrue(
                isset($actualRequiredFields[$field]),
                "Field '$field' is not highlighted with an JS error."
            );
            \PHPUnit_Framework_Assert::assertEquals(
                self::REQUIRE_MESSAGE,
                $actualRequiredFields[$field],
                "Field '$field' is not highlighted as required."
            );
        }
    }`

And block/edit/CustomerForm.php contain below code
`public function getJsErrors()
    {
        $tabs = ['account_information', 'addresses'];
        $jsErrors = [];
        foreach ($tabs as $tabName) {
            $tab = $this->getTab($tabName);
            $this->openTab($tabName);
            $jsErrors = array_merge($jsErrors, $tab->getJsErrors());
        }
        return $jsErrors;
    }`

But i am not using any Tab in my module. how to achieve above functionality

Below is the my block/edit/form.php code:

`<?php
namespace Namespace\Pincodetemplate\Test\Block\Adminhtml\Pincodetemplate\Edit;

use Magento\Mtf\Block\Form as ParentForm;

/**
 * Pincode edit form in admin.
 */
class Form extends ParentForm
{
   
   
}
`

How to assert required field?.

Thanks,

**Comment by lanken** [comment]
HI @naveenabt,
There are two possible solutions.

**Quick solution:**
Add \Magento\Backend\Test\Block\Widget\Tab::getJsErrors to your form \Namespace\Pincodetemplate\Test\Block\Adminhtml\Pincodetemplate\Edit\Form and use it in your constraints.

**Fundamental solution:**
- Create new class \Magento\Ui\Test\Block\Form which will be extended from \Magento\Mtf\Block\Form.
- Move getJsErrors() method to new class from \Magento\Backend\Test\Block\Widget\Tab.
- Change parent class for \Magento\Ui\Test\Block\Adminhtml\AbstractContainer from \Magento\Mtf\Block\Form to \Magento\Ui\Test\Block\Form.

In case of implementation second solution we appreciate a pull request to magento2/magento2ce repository.

**Comment by naveenabt** [comment]
I have extended " \Magento\Backend\Test\Block\Widget\Tab" to "\Namespace\Pincodetemplate\Test\Block\Adminhtml\Pincodetemplate\Edit\Form" class, it is working now.

Thanks lanken
