### ISSUE TITLE
Functional Test: TestStep

### ISSUE THREAD

**Issue by naveenabt** [magento/mtf#28]
Hi,

All magento testing modules  has "TestStep" folder.
What is the  use of this folder.

Thanks,

**Comment by lanken** [comment]
Hi @naveenabt,

Unfortunately this topic is not covered yet by our public documentation http://devdocs.magento.com/guides/v2.0/mtf/mtf_entities/mtf_scenariotest.html.
The main purpose of test steps is to build test scenarios like with one page checkout https://github.com/magento/magento2/blob/develop/dev/tests/functional/tests/app/Magento/Checkout/Test/etc/testcase.xml. Such approach allows to change test flow depending on available modules. For example, if the SalesRule module is enabled than to this test flow will be merged more steps from SalesRule module https://github.com/magento/magento2/blob/develop/dev/tests/functional/tests/app/Magento/SalesRule/Test/etc/testcase.xml#L9
Default test case doesn't allow to modify flow based on enabled Magento functionality, but scenario does.

There is a simple rule to decide what to use: can test flow be changed by another modules? If 'no', then you should use common test case, if answer is 'yes' then you should try scenario with test steps,

**Comment by lanken** [comment]
Closed, if you still have some questions regarding this topic, feel free to reopen.
