### ISSUE TITLE
x.commerce-user-agreement

### ISSUE THREAD

**Issue by mattisbusygithub** [magento/mtf#3]
Hello Magento/eBay (?),

Your repository for most of the projects I see under your github username at first glance, have a boiler-plate README.md file which shows up as the main information/page for each of your projects (magento2, mtf, devdocs, devdocs-code-samples, taf).

All Submissions you make to Magento, an eBay Inc. company (“Magento”) through GitHub are subject to the following terms and conditions: 

[...]

Clause 3 has a 404 URL to the License Agreement that Contributors must sign and agree to:

[quote]
You agree to the X.commerce Agreement found here:   https://www.x.com/developers/x.commerce/x.commerce-user-agreement.
[/quote]

**Comment by lanken** [comment]
README file has been updated with the latest release.
Please, check it out and reopen in case if you think additional changes are required.
