### ISSUE TITLE
functional test: Test Case time out, Test getting fail

### ISSUE THREAD

**Issue by naveenabt** [magento/mtf#30]
Hi,

I have executed create product testcase, but it is getting time out.
It is filling all information but it is not clicking on save button.

Command: vendor/bin/phpunit --filter CreateSimpleProductEntityTest --debug
Result: 
[date: 2016-05-09 08:52:46+00:00] [id: 0ce60fe2f817b9c779e7f58136b9d61a5f580c61] [state: No AppState Applied] [test suite: All Tests] [test case: Magento\Catalog\Test\TestCase\Product\CreateSimpleProductEntityTest] [test method: testCreate with data set "CreateSimpleProductEntityTestVariation1"] [stage: Main Test Flow] [url: http://magento204/admin/catalog/product/index] Timed out after 90 seconds

How to overcome above issue?
Any suggestion?

Thanks,

**Comment by lanken** [comment]
Hi @naveenabt,
Could you, please, provide a full stack trace for an error and a screenshot that shoiuld be created in dev/tests/functional/var/logs folder

**Comment by naveenabt** [comment]
Hi Lanken,

Below is the log details.

Path: /var/log/logger.log

`[date: 2016-05-10 06:25:36+00:00] [id: 6a94968fd3394bb7878a174a37d0862b8b193652] [state: No AppState Applied] [test suite: All Tests] [test case: Magento\Catalog\Test\TestCase\Product\CreateSimpleProductEntityTest] [test method: testCreate with data set "CreateSimpleProductEntityTestVariation1"] [stage: Main Test Flow] [url: http://magento2/admin/catalog/product/index] Timed out after 90 seconds`

Below is the screen shot.


![product_creation](https://cloud.githubusercontent.com/assets/18484648/15137585/6ada1f7c-16a8-11e6-856e-7ee1c1c3c85d.png)


Thanks,

**Comment by lanken** [comment]
Stack trace can be obtained by adding `--debug` option while running `phpunit`

**Comment by lanken** [comment]
Closed, as there is no response.
