### ISSUE TITLE
 Selenium and firefox version compatible

### ISSUE THREAD

**Issue by naveenabt** [magento/mtf#31]
HI,

I am using below version of Firefox and selenium.

Firefox: 45.0
selenium: selenium-server-standalone-2.48.0

is it selenium-server-standalone-2.48.0 compatible with Firefox: 45.0?

Thanks,

**Comment by lanken** [comment]
Hi @naveenabt,

If I'm not mistaken then no, please, check whether there is next error in selenium server console
'`````PHPUnit_Extensions_Selenium2TestCase_WebDriverException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output
If this error is present, please, use the latest selenium server.

**Comment by naveenabt** [comment]
Thanks Lanken.

I am not getting that error. i am getting time out error.
Please check the https://github.com/magento/mtf/issues/30

Thanks,

**Comment by lanken** [comment]
Closed the issue as there is no discussion. Feel free to reopen if it's still a problem.
