### ISSUE TITLE
Magento admin logging out automatically

### ISSUE THREAD

**Issue by naveenabt** [magento/mtf#32]
Hi Lanken,

command: vendor/bin/phpunit --debug tests/app/Magento/Catalog/Test/TestCase/Product/CreateSimpleProductEntityTest.php

If i run any test, it is logging in to backend and again it is logging out automatically so test getting fail.

any suggestion?

Thanks,

**Comment by lanken** [comment]
Hi @naveenabt,

Without stack trace error I couldn't say the reason. Please insert the error that phpunit displays after test failure.

**Comment by naveenabt** [comment]
**Hi Lanken,**
sorry, i was not mentioned error log.

**Below is the error log for "pincode create module".**

`vendor/bin/phpunit --filter CreatePincodeEntityTest --debug
PHP Warning:  Module 'OAuth' already loaded in Unknown on line 0
PHPUnit 4.1.0 by Sebastian Bergmann.

Configuration read from /var/www/magento204/htdocs/dev/tests/functional/phpunit.xml


Starting test 'CustomNamespace\Pincodetemplate\Test\TestCase\CreatePincodeEntityTest::test with data set "CreatePincodeEntityTestVariation1" (CreatePincodeEntityTestVariation1)'.
E

Time: 1.8 minutes, Memory: 54.01Mb

There was 1 error:

1) CustomNamespace\Pincodetemplate\Test\TestCase\CreatePincodeEntityTest::test with data set "CreatePincodeEntityTestVariation1" (CreatePincodeEntityTestVariation1)
PHPUnit_Extensions_Selenium2TestCase_WebDriverException: Error occurred on attempt to get element. Message: "Timed out after 90 seconds". Locator: "css selector(.page-main-actions)" . Wait: "1"
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Client/Driver/Selenium/Driver.php:157
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Client/Driver/Selenium/Driver.php:238
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Client/Element/SimpleElement.php:140
dev/tests/functional/tests/app/Magento/Backend/Test/Block/GridPageActions.php:36
dev/tests/functional/tests/app/CustomNamespace/Pincodetemplate/Test/TestCase/CreatePincodeEntityTest.php:60
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/TestCase/Injectable.php:217
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/TestCase/Functional.php:288
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/TestCase/Functional.php:202
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/TestCase/Injectable.php:201
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/TestCase/Injectable.php:158
dev/tests/functional/vendor/phpunit/phpunit/src/TextUI/Command.php:179
dev/tests/functional/vendor/phpunit/phpunit/src/TextUI/Command.php:132
                                   
FAILURES!                          
Tests: 1, Assertions: 0, Errors: 1.

`

**Below is the screenshot.**

![2552664d5eed2ed81ad856ba7d34b0427ad65bdf](https://cloud.githubusercontent.com/assets/18484648/15205182/b9a98eae-1832-11e6-8292-79ec348b19ff.png)


Here the problem is , if we run test it is logging in to magento backend and agian it is logging out automatically that is why it is not able to find the "css selector(.page-main-actions)" action button.
It is searching the action button in magento login screen.

why it is logging out automatically?

Thanks,

**Comment by lanken** [comment]
Hi @naveenabt,

Could you, please, tell me the value that you have specified in `app_backend_url` in `dev/tests/functional/phpunit.xml` and the full url after you manually log in to Magento admin.

**Comment by naveenabt** [comment]
HI Lanken,

Below is the code.

`<php>
        <env name="app_frontend_url" value="http://magento204/" />
        <env name="app_backend_url" value="http://magento204/admin/" />
        <env name="testsuite_rule" value="basic" />
        <env name="testsuite_rule_path" value="Magento/Mtf/TestSuite/InjectableTests" />
        <env name="log_directory" value="var/log" />
        <env name="events_preset" value="base" />
        <env name="module_whitelist" value="Magento_Install" />
        <env name="basedir" value="var/log" />
        <env name="credentials_file_path" value="./credentials.xml" />
        <env name="mage_mode" value="developer" />
    </php>`

Thanks,

**Comment by lanken** [comment]
I understand, that manually you can log in. Please, tell me the url that you get after manually log in to admin.

**Comment by naveenabt** [comment]
Url After login in to magento backend: http://magento204/index.php/admin/admin/dashboard/

**Comment by lanken** [comment]
Now, you can see a difference.
In phpunit
``````
<env name="app_backend_url" value="http://magento204/admin/" />
``````
and real
``````
http://magento204/index.php/admin/admin/dashboard/
``````
You should specify `index.php` in `app_backend_url`
``````
<env name="app_backend_url" value="http://magento204/index.php/admin/" />
``````
It's Magento peculiarity and how it works you can reproduce it manually if will open the same url during log in as the test does

**Comment by naveenabt** [comment]
Thanks Lanken,

You are great!!!!!!!!!!

It is working now.

Actually if we place this  http://magento204/admin/ url in browser , it will redirect to "http://magento204/index.php/admin/"

That is why i was  mentioned this.

Thanks,

**Comment by lanken** [comment]
It's my pleasure.
