### ISSUE TITLE
functional test: How to override the constraint

### ISSUE THREAD

**Issue by naveenabt** [magento/mtf#33]
Hi Lanken,

can we override constraint?
If it is yes, how we can achieve?

Thanks,

**Comment by lanken** [comment]
Hi @naveenabt,

Are you going to completely change constraint behavior or just want to ad additional verifications to some variation?

**Comment by naveenabt** [comment]
Hi Lanken,

Path: tests/functional/tests/app/Magento/Customer/Test/Constraint/AssertCustomerSuccessRegisterMessage.php

<pre>`const SUCCESS_MESSAGE = 'Thank you for registering with Main Website Store.';

    /**
     * Assert that success message is displayed after customer registered on frontend.
     *
     * @param CustomerAccountCreate $registerPage
     * @return void
     */
    public function processAssert(CustomerAccountCreate $registerPage)
    {
        $actualMessage = $registerPage->getMessagesBlock()->getSuccessMessage();
        \PHPUnit_Framework_Assert::assertEquals(
            self::SUCCESS_MESSAGE,
            $actualMessage,
            'Wrong success message is displayed.'
            . "\nExpected: " . self::SUCCESS_MESSAGE
            . "\nActual: " . $actualMessage
        );
    }`

I need change the SUCCESS_MESSAGE and some additional condition to processAssert.

Thanks,

**Comment by lanken** [comment]
Currently we don't have such ability as there was no need in it. I've created an internal ticket MTA-3317 to think have it can be done.

You can replace existing variations with this constraints in your namespace
http://devdocs.magento.com/guides/v2.0/mtf/mtf_entities/mtf_dataset.html#replace_variation

BTW, this assertion shouldn't rely on particular store name, in case if we need to check this in should be as an argument.

**Comment by naveenabt** [comment]
**Hi Lanken,**

could you please provide the example for "Replace a variation".

I am going to replace the "/dev/tests/functional/tests/app/Magento/Customer/Test/TestCase/RegisterCustomerFrontendEntityTest.xml" RegisterCustomerFrontendEntityTestVariation1 variation in custom module.

In custom name space i have created the module "Customer".

Path: customNamespace/Customer/Test

file: dev/tests/functional/tests/app/customNamespace/Customer/Test/TestCase/RegisterCustomerFrontendEntityTest.xml

<pre>
`<?xml version="1.0" encoding="utf-8"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../vendor/magento/mtf/etc/variations.xsd">
    <testCase name="Magento\Customer\Test\TestCase\RegisterCustomerFrontendEntityTest" summary="Register New Customer" ticketId="MAGETWO-23546">
        <variation name="RegisterCustomerFrontendEntityTestVariationMsg1" replace="RegisterCustomerFrontendEntityTestVariation1" summary="Register new customer">
            <data name="customer/data/firstname" xsi:type="string">john</data>
            <data name="customer/data/lastname" xsi:type="string">doe</data>
            <data name="customer/data/email" xsi:type="string">johndoe%isolation%@example.com</data>
            <data name="customer/data/is_subscribed" xsi:type="string">No</data>
            <data name="customer/data/password" xsi:type="string">123123q</data>
            <data name="customer/data/password_confirmation" xsi:type="string">123123q</data>
            <constraint name="customNamespace\Customer\Test\Constraint\AssertCustomerSuccessRegisterMessage" />
            <constraint name="Magento\Customer\Test\Constraint\AssertCustomerInGrid" />
            <constraint name="Magento\Customer\Test\Constraint\AssertCustomerLogout" />
        </variation>
    </testCase>
</config>
`
if i execute the test " vendor/bin/phpunit --filter RegisterCustomerFrontendEntityTest --debug"

**Below is the result:**

`PHPUnit 4.1.0 by Sebastian Bergmann.

Configuration read from /var/www/magento204/htdocs/dev/tests/functional/phpunit.xml

E

Time: 6.36 seconds, Memory: 20.00Mb

There was 1 error:

1) Magento\Customer\Test\TestCase\RegisterCustomerFrontendEntityTest::test
Exception: Invalid Document 
Element 'variation', attribute 'replace': The attribute 'replace' is not allowed.
Line: 10
`
any suggestion?

Thanks,

**Comment by lanken** [comment]
Sorry, I forgot that this functionality has been added in 1.0.0-rc.39 https://github.com/magento/mtf/blob/develop/CHANGELOG.md#100-rc39, but for Magento 2.0.4 MTF 1.0.0-rc37 is used.

**Comment by naveenabt** [comment]
Hi Lanken,

Thanks of the information.

How to use  updated functionality(1.0.0-rc.39) in magento  2.0.4 MTF ?
which version of magento should i use?

currently our project developing by using magento  2.0.4 and i have to use magento  2.0.4 MTF only.

please suggest?

thanks,

**Comment by naveenabt** [comment]
Hi Lanken,

can we do that?

Thanks,

**Comment by lanken** [comment]
Hi @naveenabt,

> which version of magento should i use?
This functionality is available in the develop branch. 

In order to use 1.0.0-rc.39 for 2.0.4 you need
- change magento/mtf version to 1.0.0-rc.39 in `dev/tests/functional/composer.json`
- remove `dev/tests/functional/composer.lock`
- run `composer update` in `dev/tests/functional` folder.

**Comment by naveenabt** [comment]
Thanks Lanken!!!
