### ISSUE TITLE
functional test: Assert required fields for customer registration front end

### ISSUE THREAD

**Issue by naveenabt** [magento/mtf#36]
Hi ,

How to assert the required fields for customer registration front end.

Thanks,

**Comment by lanken** [comment]
Hi @naveenabt,

What exactly do you mean?
Just press a button and verify that under some field there is a JS error message.

**Comment by naveenabt** [comment]
HI,

I am going assert the required filed for customer registration in front-end.

Below is the screenshot.

![required](https://cloud.githubusercontent.com/assets/18484648/15566335/e9bba288-233d-11e6-94b9-2f9c3f8787bb.png)

I am overriding customer testcase in my custom namesapce.

1 /var/www/magento204/htdocs/dev/tests/functional/tests/app/customNamespace/Customer/Test/TestCase/RegisterCustomerFrontendEntityTest.xml

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../vendor/magento/mtf/etc/variations.xsd">
    <testCase name="Magento\Customer\Test\TestCase\RegisterCustomerFrontendEntityTest" summary="Register New Customer" ticketId="MAGETWO-23546">
 <variation name="RegisterCustomerFrontendEntityTestVariation4" summary="Register new customer-seller/vendor option">
            <data name="customer/data/is_seller" xsi:type="string">Yes</data>
            <data name="expectedRequiredFields" xsi:type="array">
                <item name="0" xsi:type="string">First Name</item>
                <item name="1" xsi:type="string">Last Name</item>
                <item name="2" xsi:type="string">Email</item>
                <item name="3" xsi:type="string">I have read and agreed to the Terms and Conditions</item>
                <item name="4" xsi:type="string">Password</item>
                <item name="5" xsi:type="string">Confirm Password</item>
            </data>
            <constraint name="Magento\Customer\Test\Constraint\AssertCustomerFrontendRequiredFields" />
        </variation>
</testCase>
</config>
```

2 /var/www/magento204/htdocs/dev/tests/functional/tests/app/Magento/Customer/Test/Constraint/AssertCustomerFrontendRequiredFields.php


```<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

namespace Magento\Customer\Test\Constraint;

use Magento\Customer\Test\Page\CustomerAccountCreate;
use Magento\Mtf\Constraint\AbstractConstraint;

/**
 * Assert required fields on customer form.
 */
class AssertCustomerFrontendRequiredFields extends AbstractConstraint
{
    /**
     * Expected message.
     */
    const REQUIRE_MESSAGE = 'This is a required field.';

    /**
     * Assert required fields on customer form.
     *
     * @param CustomerIndexNew $customerNewPage
     * @param array $expectedRequiredFields
     * @return void
     */
    
    public function processAssert(CustomerAccountCreate $customerAccountCreate, array $expectedRequiredFields)
    {
        $actualRequiredFields = $customerAccountCreate->getRegisterForm()->getJsErrors();
        foreach ($expectedRequiredFields as $field) {
            \PHPUnit_Framework_Assert::assertTrue(
                isset($actualRequiredFields[$field]),
                "Field '$field' is not highlighted with an JS error."
            );
            \PHPUnit_Framework_Assert::assertEquals(
                self::REQUIRE_MESSAGE,
                $actualRequiredFields[$field],
                "Field '$field' is not highlighted as required."
            );
        }
    }

    /**
     * Return string representation of object.
     *
     * @return string
     */
    public function toString()
    {
        return 'All required fields on customer form are highlighted.';
    }
}

```

If ii execute the test , i am getting below error.

PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Customer\Test\Block\Form\Register::getJsErrors() in /var/www/magento204/htdocs/dev/tests/functional/tests/app/Magento/Customer/Test/Constraint/AssertCustomerFrontendRequiredFields.php:32


any suggestions?

Thanks,

**Comment by lanken** [comment]
Hi @naveenabt,

Have you added method getJsErrors() to \Magento\Customer\Test\Block\Form\Register?
Because by default there is no such method neither in \Magento\Customer\Test\Block\Form\Register nor in \Magento\Mtf\Block\Form.

**Comment by naveenabt** [comment]
I have not added.
is it predefined function or need customize getJsErrors() .?

**Comment by lanken** [comment]
No, it's not a predefined function, because in different application such JS error messages can be get in different ways, that's way it's absent in MTF itself.

The same question was in https://github.com/magento/mtf/issues/25

**Comment by naveenabt** [comment]
Thanks Lanken.
I have added getJsErrors() method.
It is working fine.

**Comment by lanken** [comment]
Closed. Feel free to reopen if you still have questions.
