### ISSUE TITLE
No open source license

### ISSUE THREAD

**Issue by mbessolov** [magento/mtf#4]
Most of the code in this repository contains the following header:
```
 * {license_notice}
 *
 * @copyright   {copyright}
 * @license     {license_link}
```
which doesn't define the license. There is no license included as a separate file either.

The absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work.

Other that a right to view the repository and fork it (both of which rights  you [granted to all GitHub users](https://help.github.com/articles/github-terms-of-service/#f-copyright-and-content-ownership) by accepting GitHub's Terms of Service and making this repository public), there is no other use for MTF now. Anybody willing to submit a pull request would effectively violate your copyright because they would have to copy your code, modify it, and publish in the form of the pull request.

This might not be what you intend. Are there any plans to publish MTF under some open source license?

**Comment by lanken** [comment]
I guess this issue has been fixed, so it can be closed.

**Comment by mbessolov** [comment]
Almost.

Now the source code files refer to COPYING.txt, which still contains the following placeholder:
"Please see <insert file name of the MEE license> for the full text" 
https://github.com/magento/mtf/blob/develop/COPYING.txt#L7

**Comment by lanken** [comment]
Please, see update license file
