### ISSUE TITLE
functional test: How to get the config data in TestStep

### ISSUE THREAD

**Issue by naveenabt** [magento/mtf#43]
I am creating test step for createSimpleProduct. 
Going to convert 'CreateSimpleProductEntityTest' to test step.

 $this->objectManager->create(
                'Magento\Config\Test\TestStep\SetupConfigurationStep', ['configData' => $this->configData]
        )->run();

How we can get the config data in test step?

**Comment by lanken** [comment]
Hi @naveenabt,

First of all, why are you going to create a step, you can use persist() method.

>> How we can get the config data in test step?

What do you mean?
Could you, please, describe what are you going to do?

**Comment by lanken** [comment]
Closed as there is no updates. Feel free to reopen if it still actual.
