### ISSUE TITLE
Invalid  Document Error

### ISSUE THREAD

**Issue by naveenabt** [magento/mtf#45]
HI,

if i run any test case i am getting below error.

There was 1 error:

1) Magento\Customer\Test\TestCase\RegisterCustomerFrontendEntity::test
Exception: Invalid Document 
Element 'testCase': Missing child element(s). Expected is ( variation ).
Line: 9

dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Config/Reader/Filesystem.php:161
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Config/Reader/Filesystem.php:120
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Config/Data.php:96
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Config/Data.php:36
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/ObjectManager/Factory.php:245
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/ObjectManager/ObjectManager.php:66
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/ObjectManager/Factory.php:155
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/ObjectManager/Factory.php:236
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/ObjectManager/ObjectManager.php:53
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Util/Iterator/TestCaseVariation.php:92
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/Util/Iterator/TestCaseVariation.php:57
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/ObjectManager/Factory.php:245
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/ObjectManager/ObjectManager.php:53
dev/tests/functional/vendor/magento/mtf/Magento/Mtf/TestCase/Injectable.php:137
dev/tests/functional/vendor/phpunit/phpunit/src/TextUI/Command.php:179
dev/tests/functional/vendor/phpunit/phpunit/src/TextUI/Command.php:132

I have checked the data set every thing is correct.

Below is the data set
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../vendor/magento/mtf/etc/variations.xsd">
    <testCase name="Magento\Customer\Test\TestCase\RegisterCustomerFrontendEntityTest" summary="Register New Customer" ticketId="MAGETWO-23546">
       <variation name="RegisterCustomerFrontendEntityTestVariation1" summary="Register new customer">
            <data name="customer/data/firstname" xsi:type="string">john</data>
            <data name="customer/data/lastname" xsi:type="string">doe</data>
            <data name="customer/data/email" xsi:type="string">johndoe%isolation%@example.com</data>
            <data name="customer/data/is_subscribed" xsi:type="string">No</data>
            <data name="customer/data/password" xsi:type="string">123123q</data>
            <data name="customer/data/password_confirmation" xsi:type="string">123123q</data>
            <constraint name="Magento\Customer\Test\Constraint\AssertCustomerSuccessRegisterMessage" />
            <constraint name="Magento\Customer\Test\Constraint\AssertCustomerInGrid" />
            <constraint name="Magento\Customer\Test\Constraint\AssertCustomerLogout" />
        </variation>
</testCase>
</config>
```
Any suggestions?

Thanks

**Comment by naveenabt** [comment]
Any suggestions?

**Comment by lanken** [comment]
Hi @naveenabt,

This code is correct, but this error is occurred when some *.xml file is invalid. Please, verify your code changes.

**Comment by naveenabt** [comment]
Thanks, i got it. Actually i have commented the variations, that is y i was getting that error.

**Comment by lanken** [comment]
Glad you've solved the problem.
