### ISSUE TITLE
credentials.xml

### ISSUE THREAD

**Issue by naveenabt** [magento/mtf#46]
Hi,

what is the use of credentials.xml file?
what types of values we can mention in credentials.xml?
What we have to mention in "name" and "replace" field?

Thanks,

**Comment by lanken** [comment]
Hi @naveenabt,

Please refer to the documentation for more details http://devdocs.magento.com/guides/v2.0/mtf/mtf_entities/mtf_fixture-repo.html#mtf_repository_credent_iso

**Comment by naveenabt** [comment]
Thanks

**Comment by lanken** [comment]
Closed, feel free to reopen if you have more questions.
