### ISSUE TITLE
Set browser that the FTF will use for tests

### ISSUE THREAD

**Issue by naveenabt** [magento/mtf#47]
Hi,

```
<server>
<item name="selenium"
      type="default"
      browser="Google Chrome"
      browserName="chrome"
      host="localhost"
      port="4444"
      seleniumServerRequestsTimeout="90"
      sessionStrategy="shared">
    <desiredCapabilities>
        <platform>ANY</platform>
    </desiredCapabilities>
</item>
</server>
```

I am having some doubts in above code.
1. can we give any port values [ port="4444"]?
2. what is  sessionStrategy="shared" and what are the possible values for sessionStrategy?
3. what is desiredCapabilities?
```
 <desiredCapabilities>
        <platform>ANY</platform>
    </desiredCapabilities>
```

Thanks,

**Comment by lanken** [comment]
Hi @naveenabt,

This is default selenium webdriver configuration, read the documentation http://docs.seleniumhq.org/docs/
1. Yes you can, but don;t to forget to change it while running webdriver
2. It's one of the selenium server parameters https://github.com/giorgiosironi/phpunit-selenium/blob/master/PHPUnit/Extensions/Selenium2TestCase.php#L257
3. https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities

**Comment by naveenabt** [comment]
Thanks lot!!!!!!!

**Comment by lanken** [comment]
Closed, please, reopen if you have questions related to browser settings.

**Comment by Muhammadyassar** [comment]
Hi.

Anyone who knows how to run the tests in headless mode?

Thanks
