### ISSUE TITLE
Getting error while installing the composer 

### ISSUE THREAD

**Issue by karthkv** [magento/mtf#51]
Hi, 

I am trying to install magento ftf , I have followed the steps mentioned in the docs
http://docs.magento.com/m1/ce/user_guide/magento/magento-test-framework.html

When i execute the command php composer.phar install  getting the below error 

C:\xampp\htdocs\magento\dev\tests\functional>php composer.phar install
  [Composer\Exception\NoSslException]
  The openssl extension is required for SSL/TLS protection but is not available. If you can not enable the openssl ex
  tension, you can disable this error, at your own risk, by setting the 'disable-tls' option to true.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
C:\xampp\htdocs\magento\dev\tests\functional>

Please suggest me how to over come this issue, if you found any easy installation steps . Please share

Thanks a lot in advance.....

**Comment by lanken** [comment]
Hi @karthkv,

Have you enabled php_openssl in the php.ini?
Please, take in to consideration that for Apache and for CLI commands different php.ini files can be used.

**Comment by karthkv** [comment]
Yeah, the mistake i had done is i have configured two environment variables of php. on adding one configuration , i have done mtf installation successfully....
Thanks , Lanken
