### ISSUE TITLE
Uncaught exception 'PHPUnit_Extensions_Selenium2TestCase_WebDriverException'

### ISSUE THREAD

**Issue by MagePsycho** [magento/mtf#6]
I am testing new MTF from Magento EE 1.14.2.0 as per:
https://github.com/magento/mtf/blob/develop/docs/install-config.md
https://github.com/magento/mtf/blob/develop/docs/running.md

When I run `phpunit` command from 'dev/tests/functional/' folder, it gives the following error:
> Fatal error: Uncaught exception 'PHPUnit_Extensions_Selenium2TestCase_WebDriverException' with > message 'Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

Firefox opens with a blank page and then above error message appears.
FYI, I am using Mac OS X 10.10.x

EDIT:
Downloading the latest version of selenium 2.45.0: http://bit.ly/1zVEa0j  fixed the issue :)

**Comment by lanken** [comment]
Closed, as a problem has been resolved.

**Comment by fetzi** [comment]
I've opened an issue on [netwing/selenium-server](https://github.com/netwing/selenium-server/issues/8) to create a tag for version 2.46.0

**Comment by lanken** [comment]
Ticket closed, as from now we are recommending to download selenium server manually from official website.
