### ISSUE TITLE
Deprecated classes

### ISSUE THREAD

**Issue by kassner** [magento/mtf#7]
Hi,

I'm trying to run functional tests for Magento 2 Beta (`1.0.0-beta` or `dev-develop`) and I stumbled upon some calls to classes suffixed with "Deprecated" like in [initApp](https://github.com/magento/mtf/blob/97175aad13c33c964082782b4a07044cc6b237c8/Magento/Mtf/Factory/Factory.php#L93) or [initBlockFactory](https://github.com/magento/mtf/blob/97175aad13c33c964082782b4a07044cc6b237c8/Magento/Mtf/Factory/Factory.php#L123).

I'm not sure why those classes are named like that, but they don't even exist, so the test run breaks with an exception:

    1) Magento\Catalog\Test\TestCase\Category\CreateCategoryEntityTest::test with data set "CreateCategoryEntityTestVariation3" (CreateCategoryEntityTestVariation3)
    ReflectionException: Class Magento\Mtf\Handler\HandlerFactoryDeprecated does not exist

Any idea?

Thanks.

**Comment by eddielau** [comment]
Hi, please cd into dev/tests/functional and run composer install. Then run "php -f dev/tests/functional/utils/generate.php"

**Comment by lanken** [comment]
@kassner, please, see the installation steps
https://github.com/magento/mtf/blob/develop/docs/install-config.md
to avoid issues with running functional tests.

**Comment by kassner** [comment]
Wonderful, I entirely missed the generate.php.

Thanks!
