### ISSUE TITLE
While executing testcases getting 'Exception: Product creation by webapi handler was not successful! Response: {"message":"Unable to save product"}'

### ISSUE THREAD

**Issue by Devanshi-pachouli** [magento/mtf#70]
Please find this attachment for the issue.
![unable to save product](https://cloud.githubusercontent.com/assets/18288575/24358111/a4160d2e-131d-11e7-839b-7c5ba6a8e16c.png)

**Comment by Rykh** [comment]
Could you, please, attach to this issue "dev/tests/functional/var/log/magento/Ui/GridFilteringTest/test with data set SalesCreditMemoGridFiltering/webapi-response/{name}.json"?

**Comment by Devanshi-pachouli** [comment]
Hello Rykh,

Please find attachment for the log file.
[Ui.zip](https://github.com/magento/mtf/files/875780/Ui.zip)

**Comment by Devanshi-pachouli** [comment]
Please find attachment for the log files.
[Ui.zip](https://github.com/magento/mtf/files/881143/Ui.zip)

**Comment by Rykh** [comment]
@Devanshi-pachouli wat version of Magento, MTF, Selenium, a browser you using? Could you, please, attach to this issue dev/tests/functional/phpunit.xml, dev/tests/functional/etc/config.xml? Also, please, attache  Magento log.

**Comment by Devanshi-pachouli** [comment]
@Rykh  Iam using Magento2.1.5. selenium-server-standalone-3.3.1, Browser is chrome with Version 57.0.2987.110 (64-bit).

[files.zip](https://github.com/magento/mtf/files/881827/files.zip)

**Comment by Rykh** [comment]
You didn't attach Magento logs (var/log on Magento side)

**Comment by Devanshi-pachouli** [comment]
Please find attachement, forgot to attach previously
[log.zip](https://github.com/magento/mtf/files/884818/log.zip)

**Comment by Rykh** [comment]
You didn't send attribute "is_active", according to Magento log 'exception.log'.
