### ISSUE TITLE
Css selector issue while executing testcase AddProductsToCartFromCustomerWishlistOnFrontendTest.php of Wishlist_(CS) group

### ISSUE THREAD

**Issue by Devanshi-pachouli** [magento/mtf#71]
While executing testcase for AddProductsToCartFromCustomerWishlistOnFrontendTest.php (wishlist group), facing css selector issue. Please help and suggest how to fix.

 Attached screenshot and log files: Please find attached.

![wishlist-issue-selenium](https://cloud.githubusercontent.com/assets/18288575/24408900/908ab028-13ec-11e7-98c8-c0fbb7b8d3ad.png)
![wishlist-issue](https://cloud.githubusercontent.com/assets/18288575/24408901/908b585c-13ec-11e7-9b1d-63cb20cc574c.png)
[Wishlist.zip](https://github.com/magento/mtf/files/875881/Wishlist.zip)

**Comment by Rykh** [comment]
What Magento/MTF version you using? According to your report, you don't have this selector on your page. How long Magento makes page load on your environment?

**Comment by lanken** [comment]
Closed, as there is no response. Feel free to reopen if it's still actual.
