### ISSUE TITLE
Admin storecode in backend urls

### ISSUE THREAD

**Issue by fetzi** [magento/mtf#8]
How can I configure **mtf** to support urls with the admin storecode in it?

*Example:*
http://foo.bar/index.php/admin/admin/customer/index

mtf would issue a request to:
http://foo.bar/index.php/admin/customer/index

Thanks,
Johannes

**Comment by lanken** [comment]
@fetzi, could you clarify what do you mean under 'admin storecode'?

**Comment by fetzi** [comment]
The tests in mtf are pointing to /admin/customer/..., but in our case the admin url is looking /admin/admin/customer/... is it possible to configure mtf to use urls like in our case?

**Comment by lanken** [comment]
Then just specify backend_url like 'http://foo.bar/index.php/admin/admin/'

**Comment by fetzi** [comment]
Thanks
